### ISSUE TITLE
Low GPU memory usage

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#37] opened 2020-01-07 22:32 UTC
Following #20, I know GPU usage is not tested, but thought I'd give it a try. 

The current issue is that it does not effectively utilize GPU. Like in the log below, you can see that the majority of the GPU memory is free: 
```
$ nvidia-smi
Tue Jan  7 14:26:02 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro RTX 8000     Off  | 00000000:17:00.0 Off |                  Off |
| 34%   38C    P8     8W / 260W |    171MiB / 48571MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro RTX 8000     Off  | 00000000:65:00.0 Off |                  Off |
| 33%   35C    P8    16W / 260W |    171MiB / 48568MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Quadro RTX 8000     Off  | 00000000:B3:00.0 Off |                  Off |
| 57%   77C    P2   259W / 260W |   3058MiB / 48571MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     25631      C   ...ransfer-transformer/env36/bin/python3.6   161MiB |
|    1     25631      C   ...ransfer-transformer/env36/bin/python3.6   161MiB |
|    2     13651      C   python                                      2887MiB |
|    2     25631      C   ...ransfer-transformer/env36/bin/python3.6   161MiB |
+-----------------------------------------------------------------------------+
```

(PS. Ignore process=13651; it's someone else's) 

The program is launched with the following command: 
```
t5_mesh_transformer  \
  --t5_tfds_data_dir="gs://danielk-files" \
  --gin_file="dataset.gin" \
  --gin_param="utils.tpu_mesh_shape.model_parallelism = 1" \
  --gin_param="utils.tpu_mesh_shape.tpu_topology = '2x2'" \
  --gin_param="MIXTURE_NAME = 'glue_mrpc_v002'" \
  --model_dir="gs://danielk-files/t5-models/" \
  --gin_file="gs://t5-data/pretrained_models/small/operative_config.gin" \
  --gin_param="tokens_per_batch=16384" 
```

My initial guess was that the batch sizes are pretty small. So, I tried changing the value of "tokens_per_batch" to bigger values, but no luck. 
Any thought?

**Comment by adarob** [comment] 2020-01-07 22:52
@nshazeer thoughts?

**Comment by adarob** [comment] 2020-01-07 23:51
I think we have a fix for this. I'll be testing it today or tomorrow.

**Comment by adarob** [comment] 2020-01-08 15:16
Duplicate of #20

**Closed by adarob** 2020-01-08 15:16 UTC
